export function sanitizeInput(input: string): string {
    return input
        .trim()
        .replace(/[<>]/g, '') // Remove potential HTML tags
        .substring(0, 1000) // Limit length
}

/**
 * Set of utility functions for sanitizing user input.
 */
export const sanitize = {
    /**
     * Escapes HTML special characters to prevent XSS.
     * 
     * @param input - The string to sanitize.
     * @returns The escaped string.
     */
    html: (input: string): string => {
        if (typeof input !== 'string') return ''
        return input
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#x27;')
            .substring(0, 10000)
    },

    /**
     * Allows basic HTML formatting (bold, italic, lists) but strips dangerous tags and attributes.
     * Used for content generated by trusted Admin rich text editors.
     */
    richText: (input: string): string => {
        if (typeof input !== 'string') return ''
        
        // Strip dangerous tags completely
        let clean = input.replace(/<\/?(script|iframe|object|embed|applet|meta|link|style|base|form)[^>]*>/gi, '');
        
        // Strip out inline event handlers (onclick, onload, etc.) and javascript: protocols
        clean = clean.replace(/(\b)(on\w+)\s*=/gi, '$1data-removed-event=');
        clean = clean.replace(/href\s*=\s*(['"]?)javascript:/gi, 'href=$1#');
        
        return clean.substring(0, 50000);
    },

    email: (input: string): string => {
        return input.toLowerCase().trim().substring(0, 254)
    },

    filename: (input: string): string => {
        return input
            .replace(/[^a-zA-Z0-9._-]/g, '_')
            .substring(0, 255)
            .replace(/^[._]/, 'file')
    },

    sql: (input: string): string => {
        return input
            .replace(/[';"\\]/g, '')
            .replace(/--/g, '')
            .replace(/\/\*|\*\//g, '')
            .trim()
            .substring(0, 1000)
    },
}
