import {
  FolderKanban,
  User,
  BriefcaseBusiness,
  Brain,
  Archive,
  Tag,
  Monitor,
  Layout,
  LayoutTemplate,
  Type,
  Music,
  MessageSquare,
  PhoneCall,
  Users,
  MessageSquareText,
  Image as ImageIcon,
} from 'lucide-react';
import type { AdminZone } from './types';

export const ADMIN_ZONES: AdminZone[] = [
  {
    id: 'content',
    label: 'Konten & Berkas',
    description: 'Kelola profil, pengalaman, keahlian, dan galeri karya',
    icon: FolderKanban,
    iconColor: 'text-blue-600',
    iconBg: 'bg-blue-500',
    gradient: 'bg-blue-600',
    apps: [
      {
        id: 'projects',
        label: 'Proyek Karya',
        icon: FolderKanban,
        iconColor: 'text-purple-600',
        iconBg: 'bg-purple-100',
        defaultWidth: 1100,
        defaultHeight: 700,
      },
      {
        id: 'profile',
        label: 'Info Profil',
        icon: User,
        iconColor: 'text-emerald-600',
        iconBg: 'bg-emerald-100',
        defaultWidth: 900,
        defaultHeight: 650,
      },
      {
        id: 'experience',
        label: 'Pengalaman',
        icon: BriefcaseBusiness,
        iconColor: 'text-emerald-600',
        iconBg: 'bg-emerald-100',
        defaultWidth: 900,
        defaultHeight: 650,
      },
      {
        id: 'skills',
        label: 'Keahlian',
        icon: Brain,
        iconColor: 'text-violet-600',
        iconBg: 'bg-violet-100',
        defaultWidth: 900,
        defaultHeight: 650,
      },
      {
        id: 'archive',
        label: 'Arsip Galeri',
        icon: Archive,
        iconColor: 'text-indigo-600',
        iconBg: 'bg-indigo-100',
        defaultWidth: 900,
        defaultHeight: 650,
      },
      {
        id: 'labels',
        label: 'Label & Tag',
        icon: Tag,
        iconColor: 'text-gray-600',
        iconBg: 'bg-gray-100',
        defaultWidth: 800,
        defaultHeight: 600,
      },
      {
        id: 'explorer',
        label: 'File Explorer',
        icon: Archive,
        iconColor: 'text-indigo-600',
        iconBg: 'bg-indigo-100',
        defaultWidth: 950,
        defaultHeight: 650,
      },
      {
        id: 'eventPages',
        label: 'Event Pages',
        icon: LayoutTemplate,
        iconColor: 'text-cyan-600',
        iconBg: 'bg-cyan-100',
        defaultWidth: 1100,
        defaultHeight: 720,
      },
    ],
  },
  {
    id: 'system',
    label: 'Sistem & Tampilan',
    description: 'Atur wallpaper, dock, widget, dan efek suara OS',
    icon: Monitor,
    iconColor: 'text-cyan-600',
    iconBg: 'bg-cyan-500',
    gradient: 'bg-cyan-600',
    apps: [
      {
        id: 'appearance',
        label: 'Tampilan',
        icon: ImageIcon,
        iconColor: 'text-cyan-600',
        iconBg: 'bg-cyan-100',
        defaultWidth: 900,
        defaultHeight: 650,
      },
      {
        id: 'dock',
        label: 'Sistem Dock',
        icon: Layout,
        iconColor: 'text-indigo-600',
        iconBg: 'bg-indigo-100',
        defaultWidth: 850,
        defaultHeight: 600,
      },
      {
        id: 'widgets',
        label: 'Widget & Catatan',
        icon: Type,
        iconColor: 'text-yellow-600',
        iconBg: 'bg-yellow-100',
        defaultWidth: 900,
        defaultHeight: 650,
      },
      {
        id: 'sounds',
        label: 'Efek Suara',
        icon: Music,
        iconColor: 'text-amber-600',
        iconBg: 'bg-amber-100',
        defaultWidth: 800,
        defaultHeight: 550,
      },
    ],
  },
  {
    id: 'communications',
    label: 'Komunikasi',
    description: 'Kelola pesan masuk, testimonial, dan info kontak',
    icon: MessageSquare,
    iconColor: 'text-green-600',
    iconBg: 'bg-green-500',
    gradient: 'bg-green-600',
    apps: [
      {
        id: 'notifications',
        label: 'WhatsApp & Notif',
        icon: MessageSquare,
        iconColor: 'text-green-600',
        iconBg: 'bg-green-100',
        defaultWidth: 1000,
        defaultHeight: 700,
      },
      {
        id: 'messages',
        label: 'Pesan Masuk',
        icon: Users,
        iconColor: 'text-indigo-600',
        iconBg: 'bg-indigo-100',
        defaultWidth: 850,
        defaultHeight: 600,
      },
      {
        id: 'feedback',
        label: 'Feedback',
        icon: MessageSquareText,
        iconColor: 'text-emerald-600',
        iconBg: 'bg-emerald-100',
        defaultWidth: 900,
        defaultHeight: 650,
      },
      {
        id: 'contacts',
        label: 'Info Kontak',
        icon: PhoneCall,
        iconColor: 'text-amber-600',
        iconBg: 'bg-amber-100',
        defaultWidth: 850,
        defaultHeight: 600,
      },
    ],
  },
];

/**
 * Map from appId to the route path whose client content will be rendered
 * inside the admin desktop window.
 */
export const APP_ROUTE_MAP: Record<string, string> = {
  projects: '/admin/projects',
  profile: '/admin/content/profile',
  experience: '/admin/content/experience',
  skills: '/admin/content/skills',
  archive: '/admin/content/archive',
  labels: '/admin/content/labels',
  explorer: '/admin/projects/explorer',
  eventPages: '/admin/projects/event-pages',
  appearance: '/admin/system/appearance',
  dock: '/admin/system/dock',
  widgets: '/admin/system/widgets',
  sounds: '/admin/system/sounds',
  notifications: '/admin/communications/notifications',
  messages: '/admin/communications/messages',
  feedback: '/admin/communications/feedback',
  contacts: '/admin/communications/contacts',
};
